[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "holos_service"
version = "0.0.1"
authors = [
  { name="Rami ALBASHA", email="ralbasha@msfourrager.com" },
]
description = "Running HOLOS 4.0 on MSF data"
readme = "README.md"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Mon-Systeme-Fourrager/holos_service"
Issues = "https://github.com/Mon-Systeme-Fourrager/holos_service/issues"