from holos_service.common import HolosVar


class LandManagementBase:
    def __init__(self):
        self.phase_number = HolosVar(name='Phase Number')
        self.name = HolosVar(name='Name')
        self.area = HolosVar(name='Area')
        self.current_year = HolosVar(name='Current Year')
        self.crop_year = HolosVar(name='Crop Year')
        self.crop_type = HolosVar(name='Crop Type')
        self.tillage_type = HolosVar(name='Tillage Type')
        self.year_in_perennial_stand = HolosVar(name='Year In Perennial Stand')
        self.perennial_stand_id = HolosVar(name='Perennial Stand ID')
        self.perennial_stand_length = HolosVar(name='Perennial Stand Length')
        self.biomass_coefficient_product = HolosVar(name='Biomass Coefficient Product')
        self.biomass_coefficient_straw = HolosVar(name='Biomass Coefficient Straw')
        self.biomass_coefficient_roots = HolosVar(name='Biomass Coefficient Roots')
        self.biomass_coefficient_extraroot = HolosVar(name='Biomass Coefficient Extraroot')
        self.nitrogen_content_in_product = HolosVar(name='Nitrogen Content In Product')
        self.nitrogen_content_in_straw = HolosVar(name='Nitrogen Content In Straw')
        self.nitrogen_content_in_roots = HolosVar(name='Nitrogen Content In Roots')
        self.nitrogen_content_in_extraroot = HolosVar(name='Nitrogen Content In Extraroot')
        self.nitrogen_fixation = HolosVar(name='Nitrogen Fixation')
        self.nitrogen_deposit = HolosVar(name='Nitrogen Deposit')
        self.carbon_concentration = HolosVar(name='Carbon Concentration')
        self.crop_yield = HolosVar(name='Yield')
        self.harvest_method = HolosVar(name='Harvest Method')
        self.nitrogen_fertilizer_rate = HolosVar(name='Nitrogen Fertilizer Rate')
        self.phosphorous_fertilizer_rate = HolosVar(name='Phosphorous Fertilizer Rate')
        self.is_irrigated = HolosVar(name='Is Irrigated')
        self.irrigation_type = HolosVar(name='Irrigation Type')
        self.amount_of_irrigation = HolosVar(name='Amount Of Irrigation')
        self.moisture_content_of_crop = HolosVar(name='Moisture Content Of Crop')
        self.moisture_content_of_crop_percentage = HolosVar(name='Moisture Content Of Crop Percentage')
        self.percentage_of_straw_returned_to_soil = HolosVar(name='PercentageOfStrawReturnedToSoil')
        self.percentage_of_roots_returned_to_soil = HolosVar(name='PercentageOfRootsReturnedToSoil')
        self.percentage_of_product_yield_returned_to_soil = HolosVar(name='PercentageOfProductYieldReturnedToSoil')
        self.is_pesticide_used = HolosVar(name='Is Pesticide Used')
        self.number_of_pesticide_passes = HolosVar(name='Number Of Pesticide Passes')
        self.manure_applied = HolosVar(name='Manure Applied')
        self.amount_of_manure_applied = HolosVar(name='Amount Of Manure Applied')
        self.manure_application_type = HolosVar(name='Manure Application Type')
        self.manure_animal_source_type = HolosVar(name='Manure Animal Source Type')
        self.manure_state_type = HolosVar(name='Manure State Type')
        self.manure_location_source_type = HolosVar(name='Manure Location Source Type')
        self.under_sown_crops_used = HolosVar(name='Under Sown Crops Used')
        self.crop_is_grazed = HolosVar(name='Crop Is Grazed')
        self.field_system_component_guid = HolosVar(name='Field System Component Guid')
        self.time_period_category_string = HolosVar(name='Time Period Category String')
        self.climate_parameter = HolosVar(name='Climate Parameter')
        self.tillage_factor = HolosVar(name='Tillage Factor')
        self.management_factor = HolosVar(name='Management Factor')
        self.plant_carbon_in_agricultural_product = HolosVar(name='Plant Carbon In Agricultural Product')
        self.carbon_input_from_product = HolosVar(name='Carbon Input From Product')
        self.carbon_input_from_straw = HolosVar(name='Carbon Input From Straw')
        self.carbon_input_from_roots = HolosVar(name='Carbon Input From Roots')
        self.carbon_input_from_extraroots = HolosVar(name='Carbon Input From Extraroots')
        self.size_of_first_rotation_for_field = HolosVar(name='Size Of First Rotation For Field')
        self.above_ground_carbon_input = HolosVar(name='Above Ground Carbon Input')
        self.below_ground_carbon_input = HolosVar(name='Below Ground Carbon Input')
        self.manure_carbon_inputs_per_hectare = HolosVar(name='Manure Carbon Inputs Per Hectare')
        self.digestate_carbon_inputs_per_hectare = HolosVar(name='Digestate Carbon Inputs Per Hectare')
        self.total_carbon_inputs = HolosVar(name='Total Carbon Inputs')
        self.sand = HolosVar(name='Sand')
        self.lignin = HolosVar(name='Lignin')
        self.w_fac = HolosVar(name='WFac')
        self.t_fac = HolosVar(name='TFac')
        self.total_nitrogen_inputs_for_ipcc_tier2 = HolosVar(name='Total Nitrogen Inputs For Ipcc Tier 2')
        self.nitrogen_content = HolosVar(name='Nitrogen Content')
        self.above_ground_residue_dry_matter = HolosVar(name='Above Ground Residue Dry Matter')
        self.below_ground_residue_dry_matter = HolosVar(name='Below Ground Residue Dry Matter')
        self.fuel_energy = HolosVar(name='Fuel Energy')
        self.herbicide_energy = HolosVar(name='Herbicide Energy')
        self.fertilizer_blend = HolosVar(name='Fertilizer Blend')
